// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVBY3DokagrsYut2SULtr9tlz0MCqT58',
    appId: '1:462253911700:web:a26ce019c44eedba6d0e81',
    messagingSenderId: '462253911700',
    projectId: 'esptrial1-e2df8',
    authDomain: 'esptrial1-e2df8.firebaseapp.com',
    databaseURL: 'https://esptrial1-e2df8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esptrial1-e2df8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VZMzuxtxomBAOFEqRizoVwZFeyYiMAQ',
    appId: '1:462253911700:android:8c2d590f9243de5f6d0e81',
    messagingSenderId: '462253911700',
    projectId: 'esptrial1-e2df8',
    databaseURL: 'https://esptrial1-e2df8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esptrial1-e2df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQIlyQeRUCcv4I2aYXjK_Qm10pCshbxI',
    appId: '1:462253911700:ios:b7bcaf3d598bed526d0e81',
    messagingSenderId: '462253911700',
    projectId: 'esptrial1-e2df8',
    databaseURL: 'https://esptrial1-e2df8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esptrial1-e2df8.firebasestorage.app',
    iosBundleId: 'com.example.motorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQIlyQeRUCcv4I2aYXjK_Qm10pCshbxI',
    appId: '1:462253911700:ios:b7bcaf3d598bed526d0e81',
    messagingSenderId: '462253911700',
    projectId: 'esptrial1-e2df8',
    databaseURL: 'https://esptrial1-e2df8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esptrial1-e2df8.firebasestorage.app',
    iosBundleId: 'com.example.motorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVBY3DokagrsYut2SULtr9tlz0MCqT58',
    appId: '1:462253911700:web:6759135493e7f9d26d0e81',
    messagingSenderId: '462253911700',
    projectId: 'esptrial1-e2df8',
    authDomain: 'esptrial1-e2df8.firebaseapp.com',
    databaseURL: 'https://esptrial1-e2df8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esptrial1-e2df8.firebasestorage.app',
  );

}